version: "3.7"

services:
  rest-api:
    build: .
    ports:
      - 80:80
    volumes:
      - ./rest-api:/var/www/html/rest-api
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    volumes:
      - ./db:/var/lib/mysql
      - ./rest-api/myblog.sql:/docker-entrypoint-initdb.d/myblog.sql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: myblog